### ISSUE TITLE
Make store_artifacts optional

### ISSUE THREAD

**Issue by nanodeath** [game-ci/unity-orb#25]
## Describe Request:

I'm using this orb to build an artifact that's then persisted to a workspace for later processing by itch.io's butler. I have `steps` that look like this:

```yaml
    steps:
      - checkout
      - unity/prepare-env
      - unity/build:
          build-name: MyGameWin64
          build-target: StandaloneWindows64
      - persist_to_workspace: 
          root: Builds
          paths:
            - StandaloneWindows64
```

However, `unity/build` automatically stores artifacts, using up valuable space in my free CircleCI account. So...it'd be cool if that was optional.
