### ISSUE TITLE
Building Unity Project Times Out

### ISSUE THREAD

**Issue by Renanse** [game-ci/unity-orb#30]
## Orb version:

1.1.0

## What happened:

I am building an Android project with Unity 2021.3.6f1 at CircleCI.  The framework terminates the job due to no output after 10 minutes.  

```
Starting: /opt/unity/Editor/Data/Tools/netcorerun/netcorerun "/opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer/AndroidPlayerBuildProgram.exe" "/opt/unity/Editor/Data/PlaybackEngines/AndroidPlayer/Bee:/opt/unity/Editor/Data/Tools/BuildPipeline" "Library/Bee/Player01afee0d.dag.json" "Library/Bee/Player01afee0d-inputdata.json" "Library/Bee/buildprogram2.traceevents"
WorkingDir: /root/project/android/unity_build
ExitCode: 0 Duration: 1s499ms
Starting: /opt/unity/Editor/Data/bee_backend --profile="Library/Bee/backend_profiler3.traceevents" --stdin-canary --dagfile="Library/Bee/Player01afee0d.dag" --continue-on-failure --dagfilejson="Library/Bee/Player01afee0d.dag.json" Player
WorkingDir: /root/project/android/unity_build
++++ trap_build_script_exit
++++ exit_status=0
++++ set +x
Compressing build artifacts...

Too long with no output (exceeded 10m0s): context deadline exceeded
```

It appears CircleCI supports customizing this timeout, but it must be passed through by the orb.  See also: https://discuss.circleci.com/t/how-to-handle-no-output-timeout-in-orb-command/44934/2

## Expected behavior:

Should build, or provide a way around the timeout.

**Comment by EricRibeiro** [comment]
Hi, @Renanse 👋 

Thank you for opening this issue. 

Per your output, Unity's build command finishes its execution. If the following is the last message you see, what is hanging is the compression step:

> Compressing build artifacts...

Can you try running the job with `compress: false`? Also, what Executor are you using?

**Comment by Renanse** [comment]
Thank you for the follow-up!  Great spot on the compress.  That actually does not show up until the process finally times out.  In the circleci interface it shows this up until canceling:

```
Starting: /opt/unity/Editor/Data/bee_backend --profile="Library/Bee/backend_profiler3.traceevents" --stdin-canary --dagfile="Library/Bee/Player01afee0d.dag" --continue-on-failure --dagfilejson="Library/Bee/Player01afee0d.dag.json" Player
WorkingDir: /root/project/android/unity_build
```

But perhaps that is the result of some output buffering or something like that?   I will give disabling compression a shot.

Here's a snippet of my config, with executor and such:

```
jobs:
  build-unity-android:
    working_directory: "~/project/android/unity_build"
    executor: 
      editor_version: 2021.3.6f1
      name: unity/ubuntu
      resource_class: large
      target_platform: android
    steps:
      - sync-submodules
      - unity/prepare-env:
          unity-password-var-name: UNITY_PASSWORD
          unity-serial-var-name: UNITY_SERIAL
          unity-username-var-name: UNITY_USERNAME
      - unity/build:
          step-name: Building KSTV in Unity for Android
          build-target: Android
          project-path: .
      - persist_to_workspace: 
          root: "./Builds/android/"
          paths:
            - UnityBuild/
```
