### ISSUE TITLE
Bump image version from 2 to 3 .1.0

### ISSUE THREAD

**Issue by Ficksik** [game-ci/unity-orb#94]
**CircleCi**

**Changes**
Bump image version

I'm running pipeline circleci and instead of 3.1.0 version 2 image is used

```
Using the v2 container runtime. For more details see: https://discuss.circleci.com/t/docker-executor-infrastructure-upgrade/52282
task-agent version 1.0.263142-53aa941e
Downloading task-agent: success after 412.402022ms.
System information:
 Server Version: 5.3.1
 Storage Driver: overlay
  Backing Filesystem: xfs
 Cgroup Driver: systemd
 Cgroup Version: 2
 Kernel Version: 6.8.0-1020-aws
 Operating System: ubuntu
 OSType: linux
 Architecture: amd64

Starting container public.ecr.aws/eks-distro/kubernetes/pause:3.6
  image is cached as public.ecr.aws/eks-distro/kubernetes/pause:3.6, but refreshing...
23d07b917726: Already exists 
8389103237f2: Already exists 
3c69a9ca2c95: Download complete 
Starting container unityci/editor:ubuntu-2022.3.17f1-android-2
Warning: No authentication provided, using CircleCI credentials for pulls from Docker Hub.
  image cache not found on this host, downloading docker.io/unityci/editor:ubuntu-2022.3.17f1-android-2

  Error pulling image unityci/editor:ubuntu-2022.3.17f1-android-2: Error response from daemon: manifest unknown: manifest unknown... retrying
  image cache not found on this host, downloading docker.io/unityci/editor:ubuntu-2022.3.17f1-android-2

  Error pulling image unityci/editor:ubuntu-2022.3.17f1-android-2: Error response from daemon: manifest unknown: manifest unknown... retrying
  image cache not found on this host, downloading docker.io/unityci/editor:ubuntu-2022.3.17f1-android-2

  Error pulling image unityci/editor:ubuntu-2022.3.17f1-android-2: Error response from daemon: manifest unknown: manifest unknown... retrying
  image cache not found on this host, downloading docker.io/unityci/editor:ubuntu-2022.3.17f1-android-2

  Error pulling image unityci/editor:ubuntu-2022.3.17f1-android-2: Error response from daemon: manifest unknown: manifest unknown... retrying
  image cache not found on this host, downloading docker.io/unityci/editor:ubuntu-2022.3.17f1-android-2

  Error pulling image unityci/editor:ubuntu-2022.3.17f1-android-2: Error response from daemon: manifest unknown: manifest unknown... retrying
  image cache not found on this host, downloading docker.io/unityci/editor:ubuntu-2022.3.17f1-android-2

Error response from daemon: manifest unknown: manifest unknown
```

My config file for circleci:
```
version: 2.1

orbs:
  unity: game-ci/unity@1.7.1

workflows:
  version: 2
  build-unity-android-project:
    when: # only execute when triggered by the api
      equal: [<< pipeline.trigger_source >>, api]
    jobs:
      # Android
      - unity/build:
          name: 'build-android'
          step-name: 'Build Android'      
          unity-license-var-name: 'UNITY_ENCODED_LICENSE'
          unity-username-var-name: 'UNITY_USERNAME'
          unity-password-var-name: 'UNITY_PASSWORD'
          executor:
            name: 'unity/ubuntu'
            target_platform: 'android'
            editor_version: '2022.3.17f1'
            resource_class: 'large'
          project-path: 'darkstarlight/darkstarlight'
          build-target: 'Android'
          context: unity
          store-artifacts: true
          build-method: 'UnityRunner.PerformBuild'
```
I see the use of the second version only in this line:
https://github.com/game-ci/unity-orb/blob/f0b6ce5ee150597a5ac27bca6e97019e7d60bd92/src/scripts/windows/prepare-env.sh#L117

I don't understand why I use this one....

**Comment by romanchikovboris** [comment]
I have same bug
Maybe it is good idea to create variable like docker_version?

My config
```
version: 2.1

orbs:
  unity: game-ci/unity@1.7.1


workflows:
  build-unity-project:
    
    parameters:
      editor_version:
        type: string
        default: '2023.1.19f1'

    jobs:

      # Playmode test
      - unity/test:
          name: Playmode test
          step-name: Playmode test
          context: MyContext
          executor:
            name: unity/ubuntu
            target_platform: webgl
            resource_class: medium
            editor_version: << parameters.editor_version >>
          test-platform: playmode 
          unity-license-var-name: UNITY_ENCODED_LICENSE
          unity-username-var-name: UNITY_USERNAME
          unity-password-var-name: UNITY_PASSWORD
```

**Comment by GabLeRoux** [comment]
The orb is outdated right now.

Relates to https://github.com/game-ci/unity-orb/issues/74

I've wrote a fix for this in https://github.com/game-ci/unity-orb/pull/83 and this was tested by some users on discord.

I basically need to merge a few changes and create a new release for it.

**Comment by Braza** [comment]
> The orb is outdated right now.
> 
> Relates to [#74](https://github.com/game-ci/unity-orb/issues/74)
> 
> I've wrote a fix for this in [#83](https://github.com/game-ci/unity-orb/pull/83) and this was tested by some users on discord.
> 
> I basically need to merge a few changes and create a new release for it.

Faced it too, even [reported ](https://discuss.circleci.com/t/cant-figure-the-correct-unity-for-android-build-config/53176)to CircleCI first, then realized I should do it here. And immediately the 1st bug at the top is my issue. Please prioritize if possible. 
Thanks!

**Comment by bd-evans** [comment]
While we wait for the release, has anyone been able to determine the latest editor compatible with image version 2?

**Comment by MohHeader** [comment]
The following comment was written by ChatGPT and copy/pasted by me. Say hi to ChatGPT 👋

### Work-around until the orb bumps to image-series **-3**

Orb v1.7.1 still hard-codes the old **“-2”** Unity images, so any editor patch that only exists on “-3” (e.g. 2022.3.62f1) fails with `manifest unknown: ... ubuntu-2022.3.62f1-<platform>-2`.

A quick fix is to define your own Docker executors pointing at the **-3** tags and use those instead of `unity/ubuntu`:

```yaml
# .circleci/config.yml
version: 2.1

orbs:
  unity: game-ci/unity@1.7.1

executors:
  unity-android-v3:
    docker:
      - image: unityci/editor:2022.3.62f1-android-3
    resource_class: large

  unity-ios-v3:
    docker:
      - image: unityci/editor:2022.3.62f1-ios-3
    resource_class: large
```

Then swap each Unity job to the matching executor:
```
build-android:
  executor: unity-android-v3     # <<<<< instead of the executor block
  steps:
    - checkout
    - unity/prepare-env
    .....

export-ios:
  executor: unity-ios-v3    # <<<<< instead of the executor block
  steps:
    - checkout
    - unity/prepare-env
    .....
```
